### ISSUE TITLE
- Create Superuser: `python manage.py shell": Permission denied issue

### ISSUE THREAD

**Issue by maxhild** [wg-lux/endoreg-client-manager#1]
INFO:root:Reading hdd config from /etc/endoreg-client-config/hdd.json
Traceback (most recent call last):
  File "/home/agl-admin/endoreg-client-manager/endoreg_client_manager/manage.py", line 23, in <module>
    main()
  File "/home/agl-admin/endoreg-client-manager/endoreg_client_manager/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/home/agl-admin/endoreg-client-manager/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/agl-admin/endoreg-client-manager/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/home/agl-admin/endoreg-client-manager/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/agl-admin/endoreg-client-manager/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agl-admin/endoreg-client-manager/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7wz6hm9i8wljz0hgwz1wqmn2zlbgavrq-python3-3.11.8/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/agl-admin/endoreg-client-manager/endoreg_client_manager/endoreg_client_manager/settings/__init__.py", line 2, in <module>
    from .default_paths import *
  File "/home/agl-admin/endoreg-client-manager/endoreg_client_manager/endoreg_client_manager/settings/default_paths.py", line 59, in <module>
    DROPOFF_DIR.mkdir()
  File "/nix/store/7wz6hm9i8wljz0hgwz1wqmn2zlbgavrq-python3-3.11.8/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/hdd-sensitive/DropOff/data'

**Comment by maxhild** [comment]
Ich versuche endoreg-client manager zu starten indem ich den superuser erstelle. Ich erhalte ein permission denied issue. Muss ich vorher noch etwas ausführen oder installieren?

**Comment by maxhild** [comment]
Hatte die Reihenfolge bei der Installation vertauscht. Installationsanleitung mit nix build, partitionsanleitung könnte ins readme oder anderweitig in die doku.
